backend:
  name: git-gateway
  branch: main


public_folder: "site"
media_folder: "site/assets"
publish_mode: editorial_workflow

collections:
  - name: "system-design"
    label: "System Design"
    folder: "docs/system-design"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
