site_name: Spring Boot and PostgreSQL system
site_url: https://dktunited.github.io/refarch-springboot-aiven
repo_url: https://github.com/dktunited/refarch-springboot-aiven
copyright: "Decathlon Technology"
use_directory_urls: true
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    primary: light blue
  font:
    text: Roboto
  favicon: assets/favicon64x64.png
  logo: assets/favicon64x64.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - awesome-pages
  - search

markdown_extensions:
  - attr_list
  - def_list
  
extra_css:
  - assets/extra.css

extra:
  version:
    provider: mike  
  homepage: /