site_name: refarch-springboot-aiven
site_url: https://dktunited.github.io/refarch-springboot-aiven
repo_url: https://github.com/dktunited/refarch-springboot-aiven
copyright: "Decathlon Technology"
use_directory_urls: true
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    primary: light blue
  font:
    text: Roboto
  favicon: assets/favicon64x64.png
  logo: assets/favicon64x64.png
nav:
    - index.md
    - 01_introduction_and_goals.md
    - 02_architecture_constraints.md
    - 03_system_scope_and_context.md
    - 04_solution_strategy.md
    - 05_building_block_view.md
    - 06_runtime_view.md
    - 07_deployment_view.md
    - 08_concepts.md
    - 'Architecture Decisions' : 09_architecture_decisions
    - 10_quality_requirements.md
    - 11_technical_risks.md
    - 12_glossary.md

plugins:
  - include_dir_to_nav

extra_css:
  - assets/extra.css

extra:
    version:
        provider: mike  
