site_name: Reference Architecture Skeleton
site_url: https://clap-demo.github.io/refarch-001/
repo_url: https://github.com/clap-demo/refarch-001
copyright: ""
use_directory_urls: true

theme:
  name: material
  palette:
    primary: light blue
  font:
    text: Roboto
  favicon: assets/favicon64x64.png
  logo: assets/favicon64x64.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - awesome-pages
  - search
  - mike

markdown_extensions:
  - attr_list
  - def_list

extra_css:
  - assets/extra.css

extra:
  version:
    provider: mike
    default: latest
  homepage: https://clap-demo.github.io/refarch-001/
