name: delete docs

"on":
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "docs/**"
      - mkdocs.yml

jobs:
  pull_request:
    runs-on: decathlon
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - name: git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: mike delete
        run: |
          mike delete --push PR-${{ github.event.number }}

