name: review

"on":
  push:
    branches:
      - '**' 

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  vale-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@v2.0.1
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        with:
          files: docs/
          vale_flags: "--minAlertLevel=warning"
          reporter: github-pr-review